---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/scottrangerio/kustomizations//vault/base
configMapGenerator:
- name: config
  files:
  - config.hcl
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: vault
  path: config-patch.yml