---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/scottrangerio/kustomizations//redis/base
configMapGenerator:
- name: config
  files:
  - redis.conf
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: redis
  path: config-patch.yml