---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/scottrangerio/kustomizations//redis/base
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: redis
  path: increased-volume.yml